runtime: nodejs20
instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.75
  min_instances: 1
  max_instances: 2

entrypoint: npm run start

env_variables:
  NODE_ENV: "production"
  PORT: "8080"

handlers:
  - url: /.*
    script: auto